### ISSUE TITLE
How to handle with empty list from the output of iucn_pull

### ISSUE THREAD

**Issue by karolazvdo** [James-Lee-998/IUCN_webscraper#1]
I've been trying to run this same code for a list of species from Africa, but when run for api_clean and some species are absence from IUCN redlist, the output is an error.

Error in `mutate()`:
! Problem while computing `category = map_chr(iucn_pull, pluck,
  "result", "category")`.
Caused by error in `stop_bad_type()`:
! Result 1 must be a single string, not NULL of length 0

As an example I'm trying for: c("Giraffa reticulata", "Pan paniscus", "Gorilla gorilla", "Lemur catta")
"Giraffa reticulata" as is absent from the redlist, I could easily remove this entry but my real list has many others, then check manually is impractible.

**Comment by James-Lee-998** [comment]
all_df = all_df%>%
  mutate(iucn_pull= map(Species, rl_search, key=apikey))%>%
  mutate(filter_nulls = map(iucn_pull, pluck, "result")) %>%
  filter(filter_nulls != 'NULL')

Just use a filter before hand

Let me know if this works

**Comment by karolazvdo** [comment]
Yeah, it works!! I tried to filter with case_when, but didn't work. Now it's all fine! Thank u!
